volumes:
  sqlite_data:

services:
  auth-service:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - sqlite_data:/data
    environment:
      - JWT_SECRET=TlFuT3JUMWNXano4N2pVN0FmU3BuamRUdFNTTzAzMndBQzRmN1BBemtlbz0K
      - SQLITE_PATH=/data/auth.db
      - PORT=8080
